server:
  port: 0

spring:
  application:
    name: order-command-service
  datasource:
    url: jdbc:h2:mem:test1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
  h2:
    console:
      enabled: true
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: command
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    enabled: false