server:
  port: 9000

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  secret: sdkfskldfmnojpewoutprigk123rkdasfk039060dkaq98l

eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
