server:
  port: 9000

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092

jwt:
  secret: sdkfskldfmnojpewoutprigk123rkdasfk039060dkaq98l

eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka
    enabled: false
  instance:
    prefer-ip-address: true
